Created IsValid Function
js-tasks-ru/jsbasic-20210520_mari-pimm84 pull request #3
Opened 2021-05-28 22:27 UTC by MarinaGvozd

Created IsValid Function

2021-05-28 22:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-29 13:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-29 13:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-29 13:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-29 19:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-29 19:50 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-05-29 19:53 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-05-30 23:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2021-05-31 00:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2021-05-31 04:07 UTC, koalex requested changes
Зачем поменяла конфиг `karma.conf.js`?

2021-05-31 04:07 UTC, koalex commented on 1-module/3-task/index.js
> +  let newStr = str[0].toUpperCase() + str.slice(1);
лучше `str.charAt(0)`

2021-05-31 04:07 UTC, koalex commented on 1-module/4-task/index.js
> +    if (lowerStr.includes('1xbet') || lowerStr.includes('xxx')) {
Можно короче: 
`return (lowerStr.includes('1xbet') || lowerStr.includes('xxx'))`

2021-05-31 04:07 UTC, koalex commented on karma.conf.js
> -      {
Надо вернуть как было

2021-05-31 15:18 UTC, MarinaGvozd commented on 1-module/3-task/index.js
> +  let newStr = str[0].toUpperCase() + str.slice(1);
спасибо

2021-05-31 15:18 UTC, MarinaGvozd commented on 1-module/4-task/index.js
> +    if (lowerStr.includes('1xbet') || lowerStr.includes('xxx')) {
Спасибо

2021-05-31 15:18 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-06-01 22:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-01 22:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2021-06-02 03:08 UTC, koalex approved these changes

2021-06-02 03:09 UTC, merged